name: Run tests
on: [push]
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_READ_TOKEN }}
jobs:
  validation-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: cd test/validations && go test
  corpus-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }} 
      - uses: workflow/nix-shell-action@v3
        with:
          packages: tree-sitter,nodejs-18_x
          script: |
            tree-sitter test
